name = "Newb RESOLUTE beta 3"
version = [0, 0, 0]
min_supported_mc_version = [1, 21, 20]
description = '''
§c%w
§7- Trying to get best visuals on a Limited Engine , BETA 3
%v
§3https://devendrn.github.io/newb-shader/
''' # %w = patch warning, %v = version
authors = ["devendrn","micheallynx"]
url = "https://devendrn.github.io/newb-shader/"
uuid = "b4a3a0f4-5d2e-4a8c-b97f-2b0b8df8a63c" # Use https://www.uuidgenerator.net/version4
materials = ["Weather","Sky","RenderChunk","SunMoon","Stars","EndSky"]
#materials = ["Weather","Sky","Clouds","SunMoon","Stars"]

[info] 
copyright = '''
Copyright © 2025 %a, and "Newb Shader" Contributors

This compiled "Newb Shader" resource pack (source code: https://github.com/devendrn/newb-x-mcbe under MIT License) is licensed under CC BY-ND 4.0 (https://creativecommons.org/licenses/by-nd/4.0/). Redistribute only unmodified copies with proper attribution to "Newb Shader" and variant creators (if any). Do not distribute derivatives.

You can compile the shader from source and distribute the result under your own terms (compatible with the MIT License).

Contact (Discord Server): https://discord.gg/newb-community-844591537430069279
''' # %a = authors
credits = '''
'''

# subpacks are arranged in left to right order
# right-most subpack is enabled by default

[[subpack]]
define = "LIGHTNING"
materials = ["Weather","Sky","RenderChunk","SunMoon","Stars","EndSky"]
description = '''
LIGHTNING\n\n\n adds shader side lightning\nImpact:Medium 
'''

[[subpack]]
define = "LEGACY_ULTRA"
materials = ["Weather","Sky","RenderChunk","SunMoon","Stars","EndSky"]
description = '''
LEGACY ULTRA\n\n\n adds dynamic semi-volumetric clouds  and adds shader computed water and puddles\nImpact: very very HIGH!!!
'''


[[subpack]]
define = "VIBRANT_ULTRA"
materials = ["Weather","Sky","RenderChunk","SunMoon","Stars","EndSky"]
description = '''
VIBRANT ULTRA\n\n\n vibrant,adds dynamic semi-volumetric clouds and adds shader computed water and puddles\nImpact: very very HIGH!!!
'''

[[subpack]]
define = "LEGACY_HIGH"
materials = ["Weather","Sky","RenderChunk","SunMoon","Stars","EndSky"]
description = '''
LEGACY HIGH\n\n\n adds dynamic lighting to cirrus clouds and adds shader computed water and puddles\nImpact:HIGH!
'''


[[subpack]]
define = "VIBRANT_HIGH"
materials = ["Weather","Sky","RenderChunk","SunMoon","Stars","EndSky"]
description = '''
VIBRANT HIGH\n\n\n vibrant,adds dynamic lighting to cirrus clouds and adds shader computed water and puddles \nImpact:HIGH!
'''

[[subpack]]
define = "VANILLA_VIBRANT"
materials = ["Weather","Sky","RenderChunk","SunMoon","Stars","EndSky"]
description = '''
VANILLA VIBRANT \n\n\n vanilla but vibrant \nImpact:LOW
'''

[[subpack]]
define = "VANILLA"
materials = ["Weather","Sky","RenderChunk","SunMoon","Stars","EndSky"]
description = '''
VANILLA\n\n\n brings back vanilla aesthetics\nImpact:LOW
'''

[[subpack]]
define = "VIBRANT"
materials = ["Weather","Sky","RenderChunk","SunMoon","Stars","EndSky"]
description = '''
VIBRANT\n\n\n makes colors more vibrant\nImpact:LOW
'''

[[subpack]]
define = "DEFAULT"
materials = []
description = '''
LEGACY
'''
